apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb 
    # This must match the label in your Deployment
  ports:
    - protocol: TCP
      port: 27017 
      targetPort: 27017
      # The port MongoDB is listening on inside the container
  type: ClusterIP

