apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  # Replace these with your actual base64 encoded values
  mongo-root-username: YWJkZWxyaG1hbg==
  mongo-root-password: MTEwMjAwMmE=


